# Generated by Django 4.2.7 on 2023-12-12 21:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("DetectionApp", "0003_detectimage_owner"),
    ]

    operations = [
        migrations.AddField(
            model_name="detectimage",
            name="predicted_image_url",
            field=models.CharField(default="url", max_length=500),
            preserve_default=False,
        ),
    ]
