# Generated by Django 4.2.7 on 2023-12-12 21:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("DetectionApp", "0004_detectimage_predicted_image_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="detectimage",
            name="date_predicted",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
