# Generated by Django 4.2.7 on 2023-12-13 00:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("DetectionApp", "0007_remove_detectimage_date_predicted_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="predictedimage",
            name="owner",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
    ]
