# Generated by Django 4.2.7 on 2023-12-19 21:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("DetectionApp", "0010_rename_detectimage_uploadimage"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="predictedimage",
            name="class_name",
        ),
        migrations.RemoveField(
            model_name="predictedimage",
            name="confidence",
        ),
        migrations.AddField(
            model_name="predictedimage",
            name="prediction_data",
            field=models.JSONField(default={"data": "no predictions"}),
            preserve_default=False,
        ),
    ]
