# Generated by Django 4.2.7 on 2024-01-04 19:49

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("DetectionApp", "0012_remove_predictedimage_date_predicted_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="PredicitonBatch",
            new_name="PredictionBatch",
        ),
    ]
