# Generated by Django 4.2.7 on 2024-01-14 21:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("DetectionApp", "0013_rename_predicitonbatch_predictionbatch"),
    ]

    operations = [
        migrations.AlterField(
            model_name="predictedimage",
            name="image",
            field=models.ImageField(upload_to="plankton/%Y/%m/%d/"),
        ),
    ]
