# Generated by Django 4.2.7 on 2024-01-05 19:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("Community", "0002_post_date_pub"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="date_added",
            field=models.DateField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
